package bot;

import javafx.animation.PauseTransition;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.util.Duration;

/**
 * Controls the chatbot's main JavaFX window.
 */
public class MainWindow extends AnchorPane {
    private static final String ERROR_PREFIX = "OOPS!!!";
    private static final Duration EXIT_DELAY = Duration.seconds(1);
    private static final String WELCOME_MESSAGE = "Hi! I'm Bot. What can I help you with?";

    private final Image botImage = new Image(getClass().getResourceAsStream("/images/Bot.jpg"));

    @FXML
    private ScrollPane scrollPane;
    @FXML
    private VBox dialogContainer;
    @FXML
    private TextField userInput;
    @FXML
    private Button sendButton;

    private Bot bot;

    /**
     * Creates the controller used by the FXML loader.
     */
    public MainWindow() {
    }

    /**
     * Connects the scroll position to the dialog container's height.
     */
    @FXML
    public void initialize() {
        dialogContainer.heightProperty().addListener((observable, oldHeight, newHeight) -> scrollPane.setVvalue(1.0));
    }

    /**
     * Injects the chatbot used to generate responses.
     *
     * @param bot chatbot instance used by this window.
     */
    public void setBot(Bot bot) {
        this.bot = bot;
        dialogContainer.getChildren().add(DialogBox.getBotDialog(WELCOME_MESSAGE, botImage));
        if (!bot.getStartupMessage().isEmpty()) {
            dialogContainer.getChildren().add(createBotDialog(bot.getStartupMessage()));
        }
        Platform.runLater(userInput::requestFocus);
    }

    /**
     * Displays the user's message and Bot's response, then clears the input field.
     */
    @FXML
    private void handleUserInput() {
        String userText = userInput.getText();
        String botText = bot.getResponse(userText);

        if (!userText.isBlank()) {
            dialogContainer.getChildren().add(DialogBox.getUserDialog(userText));
        }
        dialogContainer.getChildren().add(createBotDialog(botText));
        userInput.clear();
        userInput.requestFocus();

        if (bot.shouldExit()) {
            exitAfterGoodbye();
        }
    }

    /**
     * Creates either a standard reply or an emphasized error dialog.
     *
     * @param response response generated by Bot.
     * @return dialog styled for the response type
     */
    private DialogBox createBotDialog(String response) {
        if (response.startsWith(ERROR_PREFIX)) {
            return DialogBox.getErrorDialog(response, botImage);
        }
        return DialogBox.getBotDialog(response, botImage);
    }

    /**
     * Disables further input and closes the application after showing the farewell response.
     */
    private void exitAfterGoodbye() {
        userInput.setDisable(true);
        sendButton.setDisable(true);

        PauseTransition exitDelay = new PauseTransition(EXIT_DELAY);
        exitDelay.setOnFinished(event -> Platform.exit());
        exitDelay.play();
    }
}
